# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 566f95a0f64f14943afbf08ee1b21db13acb781f2dbd7939516eb68ccfe0eb5d1c96c71f2fedaa60aeaa72a248fddab31102dd6ddc664532fb1034b4b9e7a16e

test:
  secret_key_base: 02299de1eea0bc30b2114d02325bc2e8e1de769fa20abe9a063e2e833b93d1f3e479ede2bd666245c981b762d0e87371cb7f5ae04aee4973f4304f47a2194d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
